version: '3'

volumes:
  aivodb:
    driver: local

services:

  api:
    build:
        context: .
        dockerfile:  docker/api/Dockerfile
    command: "python app.py"
    container_name: api-aivo
    depends_on:
      - db
    env_file:
      - "docker/api/.env"
    ports:
      - "5000:${PORT:-5000}"
    volumes:
      - ".:/app"

  db:
    container_name: db-aivo
    build:
        context: .
        dockerfile: docker/db/Dockerfile
    env_file:
      - "docker/db/.env"
    ports:
      - "5433:5432"
    volumes:
      - aivodb:/var/lib/postgresql/data/